<?php
/**
 * @author     : lims
 * @date       : 2024-12-18
 * @version    : 1.0
 * description :
 */
namespace  backend\controllers;

use Yii;
use yii\web\Controller;
use yii\web\Response;

class BaseController extends  Controller
{

    protected $_format = Response::FORMAT_JSON;

    public function  beforeAction($action)
    {
        if (\Yii::$app->user->isGuest){
            $this->goHome();
            return false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * 返回成功
     * @param array $data
     * @param string $message
     * @return Response
     */
    public function returnSuccess($data = [], $message = '操作成功')
    {
        $this->response->format = $this->_format;
        $this->response->data = [
            'code' => 200,
            'msg' => Yii::t('app', $message),
            'data' => $data,
        ];
        return $this->response;
    }


    /**
     * 返回错误
     * @param string $message
     * @param int $code
     * @param array $data
     * @return Response
     */
    public function returnError($message = '操作失败，请稍后重试', $code = 500, $data = [])
    {
        $this->response->format = $this->_format;
        $this->response->data = [
            'code' => $code,
            'msg' => Yii::t('app', $message),
            'data' => $data,
        ];
        return $this->response;
    }
}
