<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "{{%email}}".
 *
 * @property int $id
 * @property int $user_id
 * @property string $subject 标题
 * @property string $body 内容
 * @property string $files 上传附件
 * @property int $is_success
 * @property int $type
 * @property int $status 状态
 * @property int $create_at
 * @property int $update_at
 * @property string from
 * @property string to
 * @property int send_time
 */
class Email extends \yii\db\ActiveRecord
{
    /**
     * @var int|mixed|string|null
     */


    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
//        return '{{%email}}';
        return 'admin_email';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['to','subject','body'], 'required'],
            [['id', 'user_id', 'is_success', 'type', 'status', 'create_at', 'update_at'], 'integer'],
            [['body','from'], 'string'],
            [['subject'], 'string', 'max' => 255],
            [['files'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, pdf'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', '添加人'),
            'to' => Yii::t('app', '收件人'),
            'from' => Yii::t('app', '发件人'),
            'subject' => Yii::t('app', '标题'),
            'body' => Yii::t('app', '内容'),
            'files' => Yii::t('app', '附件'),
            'is_success' => Yii::t('app', 'Is Success'),
            'type' => Yii::t('app', 'Type'),
            'status' => Yii::t('app', 'Status'),
            'create_at' => Yii::t('app', '创建时间'),
            'update_at' => Yii::t('app', '修改时间'),
            'send_time' => Yii::t('app', '实际发送'),
            'order_time' => Yii::t('app', '预约时间'),
        ];
    }

    public function  beforeSave($insert)
    {
        $this->to = is_array($this->to) ? implode(',',$this->to) : $this->to;//如果是多个收件人 用逗号隔开

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}
